### ISSUE TITLE
Code does not work in Widgets

### ISSUE THREAD

**Issue by FahadUddin92** [acekyd/display-medium-posts#1]
I tried to add shortcode widget in functions.php and then add it in Widgets. Its not showing anything.

**Comment by veeren9** [comment]
Add below code in functions and then add short code in sidebar widget.

// Enable shortcodes in text widgets
add_filter('widget_text','do_shortcode');

**Comment by acekyd** [comment]
Oh i must have missed this issue... Apologies @FahadUddin92... Thanks for the response @veeren9, i'd definitely love a pull request :)

**Comment by veeren9** [comment]
@acekyd your welcome.

**Comment by acekyd** [comment]
@veeren9 would you be submitting a pull request for this?

**Comment by veeren9** [comment]
@acekyd , sorry I don't know how to do that, I am new here.
