### ISSUE TITLE
Shows "No Posts found!" message

### ISSUE THREAD

**Issue by sebastianzillessen** [acekyd/display-medium-posts#11]
When I integrate the plugin with `[display_medium_posts handle="@acekyd"]` I get the message "No Posts found!".

Is there any way of debugging or checking why this happens?

Thanks!

**Comment by sebastianzillessen** [comment]
Hi, is there any update on this issue?

**Comment by acekyd** [comment]
Hello @sebastianzillessen, I apologize for not giving feedback earlier. I tried exactly the above shortcode on multiple installations and it works fine. I can only make a few guesses to determine what went wrong with yours. Have you tried another Medium username? Are you on shared hosting? Can you attach a screenshot of your implementation and where it is displayed

**Comment by sebastianzillessen** [comment]
Hi,

I figured it out in the meantime. 
Problem was, that my php was configured not to allow_url_fopen. After debugging through your code I figured out that this was the problem. Maybe a more sophisticated message could help others do fix this. 

I gonna try submitting a pull request layer with my changes as I added this error message. I'll keep u posted! 

Best, 

Sebastian 



--
Sebastian Zillessen 
(+41 (0) 79 567 29 19)

**Comment by acekyd** [comment]
Awesome @sebastianzillessen. That would be much appreciated 😄

**Comment by japhigu** [comment]
I have the same issue - I have confirmed with my hosting provider that allow_url_fopen() is active but it still doesn't work. 

Do you have any ideas ? @acekyd

**Comment by acekyd** [comment]
The new update would be pushing to use curl instead. This should fix the issue @le-dawg

**Comment by YonatanKra** [comment]
Have this issue as well.
