### ISSUE TITLE
Feed is showing on top of page and not where i put it? 

### ISSUE THREAD

**Issue by stefansoelbeck** [acekyd/display-medium-posts#2]
Im trying to use this plugin to show Medium posts on my wordpress. The plugin is showing the posts i want. But they are showing on top of the page and not where i put the shortcode? What am i doing wrong?

**Comment by acekyd** [comment]
@stefansoelbeck Your page structure and styling may have something to do with this... Are you using a custom template? Or share a link to your template with me so i can look into it from here

**Comment by stefansoelbeck** [comment]
@acekyd Im very new to this so please forgive me if i ask stupid questions. Im using the theme Flatsome Child and have been using the build in UX Builder to create the composition. When i use the edit page i put in the shortcode [display_medium_posts handle="@futnav" display=4 total=10] where it should be compared to the other shortcodes being created by the UX Builder. I see the Medium posts.. but not where they should be..

**Comment by acekyd** [comment]
Hello @stefansoelbeck. Not really sure what's going on... I'd have to assume it's the UX Builder causing issues. However, it's been almost a month since you had this issue, any updates since then?
