### ISSUE TITLE
Filter publication posts by tags

### ISSUE THREAD

**Issue by svenefftinge** [acekyd/display-medium-posts#20]
It would be good, to be able to provide a list of tags, so that only those stories are included which are tagged with at least one of them.

**Comment by lariobyte** [comment]
I think so too. It would be a great update!

**Comment by acekyd** [comment]
Thanks @svenefftinge @lariobyte Just added this to the new version. Should be possible on next update.

However, only one tag can be specified at a time. Medium limitations.

**Comment by faithg0328** [comment]
how do I only list a specific tag? Thanks
