### ISSUE TITLE
The plugin suddenly stopped working

### ISSUE THREAD

**Issue by Skothari123** [acekyd/display-medium-posts#28]
Hi,

The plugin was installed in the footer of our website - www.finturi.com
But suddenly the posts dont appear.

**Comment by rikmendes** [comment]
Same here..always been working fine until now..no matter what I change in the short code, there is no post to display, even from a tag from medium wide content..

**Comment by Skothari123** [comment]
@rikmendes Is it working for you now? Its not working for me.

**Comment by Skothari123** [comment]
@acekyd Can you please help?

**Comment by rikmendes** [comment]
Not working here.. Isn't there a WP plug-in update to do first? Ricardo Mendeswww.rmendes.net On 9 Sep 2019 14:34, Skothari123 <notifications@github.com> wrote:@rikmendes Is it working for you now? Its not working for me.

**Comment by cleanforestco** [comment]
I have the same issue. Plugin suddenly stopped working. Running Version 4.0.

**Comment by aims007** [comment]
Having the same issue. On two of my sites. Would super appreciate an update / fix.

Running plugin version 4.0 and WP v5.2.3.

Thank you so much.

**Comment by davecocoa** [comment]
Same problem here, I reckon it's because Medium have put a reCAPTCHA in front of the latest posts endpoint, so robots (like this plugin) can't access it any more.

I suggest taking it up with Medium, although I wouldn't be overly hopeful about them re-opening the endpoint for robots.

**Comment by zzkovacs** [comment]
Same problem here. Is there any progress to fix this issue?

**Comment by wvanstraalen** [comment]
Yes, I would like to know if this will be updated in the future or that I can better find another solution to posting my Medium posts on my WordPress Blog

**Comment by acekyd** [comment]
Hello @francesmcmullin @wvanstraalen @zzkovacs @cleanforestco @rikmendes @Skothari123 

This plugin has now been updated with numerous suggestions from users. Thanks a lot. Medium's captcha was preventing access and I had been unavailable to factor an alternative. Should work great now. Huge thanks to @cleanforestco for the code sample as well. Cheers

**Comment by wvanstraalen** [comment]
Thanks a ton! I will be curious to give it a try tomorrow! 

For me it was a great way to add a blog to my website that would be independent from the latest posts on the homepage. 
I know there are other workarounds, but I liked to possibility to be on two mediums at the same time and harness the strengths of each one.

Once again, much appreciate taking the initiative to create such a cool plugin, it is an inspiration to me!
Op 25 mei 20:07:01, Adewale Abati <notifications@github.com> schreef:
Hello @francesmcmullin [https://github.com/francesmcmullin] @wvanstraalen [https://github.com/wvanstraalen] @zzkovacs [https://github.com/zzkovacs] @cleanforestco [https://github.com/cleanforestco] @rikmendes [https://github.com/rikmendes] @Skothari123 [https://github.com/Skothari123]
This plugin has now been updated with numerous suggestions from users. Thanks a lot. Medium's captcha was preventing access and I had been unavailable to factor an alternative. Should work great now. Huge thanks to @cleanforestco [https://github.com/cleanforestco] for the code sample as well. Cheers
