### ISSUE TITLE
Getting Error on line - 104 and 114

### ISSUE THREAD

**Issue by veeren9** [acekyd/display-medium-posts#4]
When activating the plugin getting error on line 104 and 114 in "display-medium-posts.php"

And most of the info not coming or broken.

Notice: Undefined property: stdClass::$snippet in /Users/veeren/Documents/projects/podcast/website/wp-content/plugins/display-medium-posts/display-medium-posts.php on line 104

Notice: Undefined property: stdClass::$createdAtRelative in /Users/veeren/Documents/projects/podcast/website/wp-content/plugins/display-medium-posts/display-medium-posts.php on line 114

Screenshot attached :

![screen shot 2017-03-06 at 11 28 04 am](https://cloud.githubusercontent.com/assets/24691007/23598403/266447ce-0260-11e7-9fe1-d33436a46e5b.png)

**Comment by acekyd** [comment]
Hello @veeren9, what version are you using? Please update your plugin to the latest version to get the fix. Thanks.
